### ISSUE TITLE
Navbar Links on index and contact page

### ISSUE THREAD

**Issue by UsmanUet276** [UsmanUet276/Hacktoberfest23-Project#12]
We have to update Nav Links for mobile and Desktop version
Add ```Home``` and ```Contact Us``` link and add them to navbar of ```index.html``` and ```contact.html```

**Comment by nrj-kmr** [comment]
Please assign this issue to me @UsmanUet276

**Comment by UsmanUet276** [comment]
Completed @nrj-kmr good work
