### ISSUE TITLE
"Contact" section on footer should take user to the Contact.html page 

### ISSUE THREAD

**Issue by RGupta-design** [UsmanUet276/Hacktoberfest23-Project#13]

**Comment by UsmanUet276** [comment]
Hey @RGupta-design its good to take user to ```contact.html``` from contact section but its not good practice to remove ```Home``` nav link from navbar so I am editing and approving your issue.
If you want to assign this issue to you  so please comment.

**Comment by RGupta-design** [comment]
Yes, please assign this issue to me.

**Comment by UsmanUet276** [comment]
Completed and merged
